### ISSUE TITLE
[urgent bug] Namecard_modern bug

### ISSUE THREAD

**Issue by GardenJWKIM** [iamjinhyoungjoo/skku-namecard-generator#4]
![image](https://user-images.githubusercontent.com/101326648/169560055-4e7db3f9-20a3-4774-bb26-e2abc622ab3b.png)

In the process of creating the "modern namecard", the border is not visible.

![image](https://user-images.githubusercontent.com/101326648/169560126-3f15a11a-2152-4f1c-bad2-72cd1b90044b.png)

The background disappeared while modifying the "rect" value of the code.

**Comment by iamjinhyoungjoo** [comment]
Fixed bug
